/*-------------------------------------------------------------------------
 *
 * communicator_process.c
 *	  Functions for starting up the communicator background worker process.
 *
 * Currently, the communicator process only functions as a metrics
 * exporter. It provides an HTTP endpoint for polling a limited set of
 * metrics. TODO: In the future, it will do much more, i.e. handle all
 * the communications with the pageservers.
 *
 * Portions Copyright (c) 1996-2021, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include <unistd.h>

#include "miscadmin.h"
#include "postmaster/bgworker.h"
#include "postmaster/bgwriter.h"
//#include "postmaster/interrupt.h"
#include "postmaster/postmaster.h"
#include "replication/walsender.h"
#include "storage/ipc.h"
#include "storage/latch.h"
#include "storage/pmsignal.h"
#include "storage/procsignal.h"
#include "tcop/tcopprot.h"
#include "utils/timestamp.h"

#include "communicator_process.h"
#include "file_cache.h"
#include "neon.h"
#include "neon_perf_counters.h"
#include "libpq/pqsignal.h"
#include "gssignal/gs_signal.h"
#include "pgstat.h"
#include "wait_events.h"

/* the rust bindings, generated by cbindgen */
#include "communicator/communicator_bindings.h"
static void pump_logging(struct LoggingReceiver *logging);
PGDLLEXPORT void communicator_new_bgworker_main(Datum main_arg);

/**** Initialization functions. These run in postmaster ****/

/*
 * Initialize communicator process (stage 1: _PG_init).
 * This function only does early initialization that doesn't require
 * shared memory. The actual bgworker registration is deferred to
 * communicator_register_bgworker() which is called from shmem_startup_hook.
 */
void
pg_init_communicator_process(void)
{
	/* Early initialization only - bgworker registration happens later */
	/* No-op for now, but kept for compatibility */
}

/*
 * Communicator bgworker entry point for OpenGauss (uses BgWorkerContext).
 * This is the adapter function that bridges OpenGauss bgworker API to
 * the existing communicator_new_bgworker_main logic.
 */
static void
communicator_new_bgworker_main_OpenGauss(const BgWorkerContext *bwc)
{
	/* Call the main logic, passing 0 as main_arg since we don't use it */
	communicator_new_bgworker_main((Datum) 0);
}

/*
 * Register communicator background worker (stage 3: shmem_startup_hook).
 * This function should be called after InitBgworkerGlobal() has been called,
 * i.e., after CreateSharedMemoryAndSemaphores() in postmaster startup.
 */
void
communicator_register_bgworker(void)
{
	BgWorkerContext bwc;

	memset(&bwc, 0, sizeof(bwc));
	
	/* Set the main entry point function for OpenGauss bgworker */
	bwc.main_entry = communicator_new_bgworker_main_OpenGauss;
	
	/* Optional: Set exit entry point if needed (can be NULL) */
	bwc.exit_entry = NULL;
	
	/* Optional: Set database and user name if needed */
	/* bwc.databaseName = pstrdup("postgres"); */
	/* bwc.userName = pstrdup("cloud_admin"); */
	
	/* Optional: Set flag for individual thread mode if needed */
	bwc.flag = 0;
	
	/* Register the background worker with OpenGauss API */
	if (!RegisterBackgroundWorker(&bwc, 0))
	{
		ereport(WARNING, (errmsg("Failed to register communicator background worker")));
	}
}

/**** Worker process functions. These run in the communicator worker process ****/

/*
 * Entry point for the communicator bgworker process
 */
void
communicator_new_bgworker_main(Datum main_arg)
{
	struct LoggingReceiver *logging;
	const char *errmsg = NULL;
	const struct CommunicatorWorkerProcessStruct *proc_handle;

	//TODO:暂时屏蔽pg代码
	/*
	 * Pretend that this process is a WAL sender. That affects the shutdown
	 * sequence: WAL senders are shut down last, after the final checkpoint	
	 * has been written. That's what we want for the communicator process too.
	 */
	t_thrd.walsender_cxt.am_walsender = true;
	MarkPostmasterChildWalSender();

	/* Establish signal handlers. */
	gspqsignal(SIGUSR1, procsignal_sigusr1_handler);
	/*
	 * Postmaster sends us SIGUSR2 when all regular backends and bgworkers
	 * have exited, and it's time for us to exit too
	 */
	gspqsignal(SIGUSR2, die);
	gspqsignal(SIGHUP, bgwriter_sighup_handler);
	gspqsignal(SIGTERM, die);

	PG_SETMASK(&t_thrd.libpq_cxt.UnBlockSig);

	/*
	 * By default, INFO messages are not printed to the log. We want
	 * `tracing::info!` messages emitted from the communicator to be printed,
	 * however, so increase the log level.
	 *
	 * XXX: This overrides any user-set value from the config file. That's not
	 * great, but on the other hand, there should be little reason for user to
	 * control the verbosity of the communicator. It's not too verbose by
	 * default.
	 */
	SetConfigOption("log_min_messages", "INFO", PGC_SUSET, PGC_S_OVERRIDE);

	logging = communicator_worker_configure_logging();

	proc_handle = communicator_worker_launch(
		neon_tenant[0] == '\0' ? NULL : neon_tenant,
		neon_timeline[0] == '\0' ? NULL : neon_timeline,
		&errmsg
		);
	if (proc_handle == NULL)
	{
		/*
		 * Something went wrong. Before exiting, forward any log messages that
		 * might've been generated during the failed launch.
		 */
		pump_logging(logging);

		elog(PANIC, "%s", errmsg);
	}

	/*
	 * The Rust tokio runtime has been launched, and it's running in the
	 * background now. This loop in the main thread handles any interactions
	 * we need with the rest of PostgreSQL.
	 *
	 * NB: This process is now multi-threaded! The Rust threads do not call
	 * into any Postgres functions, but it's not entirely clear which Postgres
	 * functions are safe to call from this main thread either. Be very
	 * careful about adding anything non-trivial here.
	 *
	 * Also note that we try to react quickly to any log messages arriving
	 * from the Rust thread. Be careful to not do anything too expensive here
	 * that might cause delays.
	 */
	elog(LOG, "communicator threads started");
	for (;;)
	{
		TimestampTz before;
		long		duration;

		ResetLatch(&t_thrd.proc->procLatch);

		/*
		 * Forward any log messages from the Rust threads into the normal
		 * Postgres logging facility.
		 */
		pump_logging(logging);

		/*
		 * Check interrupts like system shutdown or config reload
		 *
		 * We mustn't block for too long within this loop, or we risk the log
		 * queue to fill up and messages to be lost. Also, even if we can keep
		 * up, if there's a long delay between sending a message and printing
		 * it to the log, the timestamps on the messages get skewed, which is
		 * confusing.
		 *
		 * We expect processing interrupts to happen fast enough that it's OK,
		 * but measure it just in case, and print a warning if it takes longer
		 * than 100 ms.
		 */
#define LOG_SKEW_WARNING_MS			100
		before = GetCurrentTimestamp();

		CHECK_FOR_INTERRUPTS();
		if (t_thrd.bgwriter_cxt.got_SIGHUP)
		{
			t_thrd.bgwriter_cxt.got_SIGHUP = false;
			ProcessConfigFile(PGC_SIGHUP);
		}

		long sens;
		int usecs;

		TimestampDifference(before, GetCurrentTimestamp(), &sens, &usecs);

		duration = sens * 1000 + usecs / 1000;
		if (duration > LOG_SKEW_WARNING_MS)
			elog(WARNING, "handling interrupts took %ld ms, communicator log timestamps might be skewed", duration);

		/*
		 * Wait until we are woken up. The rust threads will set the latch
		 * when there's a log message to forward.
		 */
		(void) WaitLatch(&t_thrd.proc->procLatch,
						 WL_LATCH_SET | WL_EXIT_ON_PM_DEATH,
						 0);
	}
}

static void
pump_logging(struct LoggingReceiver *logging)
{
	char		errbuf[1000];
	int			elevel;
	int32		rc;
	static uint64_t last_dropped_event_count = 0;
	uint64_t		dropped_event_count;
	uint64_t		dropped_now;

	for (;;)
	{
		rc = communicator_worker_poll_logging(logging,
											  errbuf,
											  sizeof(errbuf),
											  &elevel,
											  &dropped_event_count);
		if (rc == 0)
		{
			/* nothing to do */
			break;
		}
		else if (rc == 1)
		{
			/* Because we don't want to exit on error */
			
			//TODO:日志是否值得打印
			// if (message_level_is_interesting(elevel))
			if(elevel >= ERROR)
			{
				/*
				 * Prevent interrupts while cleaning up.
				 *
				 * (Not sure if this is required, but all the error handlers
				 * in Postgres that are installed as sigsetjmp() targets do
				 * this, so let's follow the example)
				 */
				HOLD_INTERRUPTS();

				errstart(elevel, __FILE__, __LINE__, PG_FUNCNAME_MACRO, TEXTDOMAIN);
				errmsg_internal("[COMMUNICATOR] %s", errbuf);
				EmitErrorReport();
				FlushErrorState();

				/* Now we can allow interrupts again */
				RESUME_INTERRUPTS();
			}
		}
		else if (rc == -1)
		{
			elog(ERROR, "logging channel was closed unexpectedly");
		}
	}

	/*
	 * If the queue was full at any time since the last time we reported it,
	 * report how many messages were lost. We do this outside the loop, so
	 * that if the logging system is clogged, we don't exacerbate it by
	 * printing lots of warnings about dropped messages.
	 */
	dropped_now = dropped_event_count - last_dropped_event_count;
	if (dropped_now != 0)
	{
		elog(WARNING, "%lu communicator log messages were dropped because the log buffer was full",
			 (unsigned long) dropped_now);
		last_dropped_event_count = dropped_event_count;
	}
}

/****
 * Callbacks from the rust code, in the communicator process.
 *
 * NOTE: These must be thread-safe! It's very limited which PostgreSQL
 * functions you can use!!!
 *
 * The signatures of these need to match those in the Rust code.
 */

void
callback_set_my_latch_unsafe(void)
{
	//TODO:暂时屏蔽PG代码
	SetLatch(&t_thrd.proc->procLatch);
}
